### ISSUE TITLE
Error on test

### ISSUE THREAD

**Issue by Tovo-Adagp** [Vivify-Ideas/nestjs-boilerplate#1]
When I run npm test on default procject I get **[ExceptionHandler] In order to use "defaultStrategy", please, ensure to import PassportModule in each place where AuthGuard() is being used. Otherwise, passport won't work correctly.**

**Comment by nikolasp** [comment]
Hi @Tovo-Adagp,

This is just warning, but everything should work.
However, if you want to remove this message just change in `app.controller.ts` file line 12 from `@UseGuards(AuthGuard())` to `@UseGuards(AuthGuard('jwt'))`
The message will magically disappear. :)

Thanks for the feedback!

**Comment by raghavpruthi** [comment]
great thanks for your help @nikolasp
