### ISSUE TITLE
request /api/auth/me response "401 Unauthorized" 

### ISSUE THREAD

**Issue by lazy1523** [Vivify-Ideas/nestjs-boilerplate#6]
request /api/auth/me response "401 Unauthorized" 
but i already set header “Authorization" token for login response

my curl
curl -X GET "http://localhost:3000/api/auth/me" -H "accept: application/json" -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTY4NTU5MzE4LCJleHAiOjE1Njg1NjI5MTh9.Irmkw2p2I_MiLcAxEqTpIR0GBhaDFbSYF3P4-ew5XEM"

but response "401 Unauthorized"  

I hope to get a reply 
Thank you

**Comment by nikolasp** [comment]
Hi @lazy1523,

Thanks for the feedback. 

Just add Bearer prefix before the actual token. 
'Authorization: Bearer {token}'

**Comment by lazy1523** [comment]
oh!~~ Thanks you!!! 

Is my mistake

thank you very much
